export const plusIcon: string = "add-icon.svg" // +
export const AscIcon: string = "ascending-icon.svg" // table asc icon
export const AscSelIcon: string = "ascending-selected-icon.svg" // table selected asc icon
export const Dataicon: string = "data-icon.svg" // empty table icon
export const DescIcon: string = "descending-icon.svg" // table desc icon
export const DescSelIcon: string = "descending-selected-icon.svg" // table selected desc icon
export const DotMenuFileIcon: string = "dot-menu-file-icon.svg" // table right end 3-dots menu file
export const DotMenuFolderIcon: string = "dot-menu-folder-icon.svg" // table right end 3-dots menu folder
export const DownIcon: string = "down-icon.svg" // arrow down for page size dropdown
export const FileIcon: string = "file-icon.svg" // table file type icon
export const FolderIcon: string = "folder-icon.svg" //table folder type icon
export const LeftArrowDisabledIcon: string = "left-arrow-disabled-icon.svg" // pagination left arrow disabled
export const LeftArrowIcon: string = "left-arrow-icon.svg" // pagination left arrow
export const RightArrowDisabledIcon: string = "right-arrow-disabled-icon.svg" // pagination right arrow disabled
export const RightArrowIcon: string = "right-arrow-icon.svg" // pagination right arrow
export const SearchIcon: string = "search-icon.svg" // search box icon
export const UpIcon: string = "up-icon.svg" // arrow up for page size dropdown
export const UploadIcon: string = "upload-icon.svg" // file upload button icon